language: minimal
sudo: false
notifications:
  email:
    - tbekolay@gmail.com

env:
  global:
    - MODE="test"
    - NUMPY="1.14"
    - SCIPY="false"
    - COVERAGE="false"

jobs:
  include:
    - stage: basic
      env: MODE="static" PYTHON="2.7"
    - env: MODE="test" PYTHON="2.7" COVERAGE="true"
    - stage: advanced
      env: MODE="test" PYTHON="2.7" NUMPY="1.11"
    - env: MODE="test" PYTHON="2.7" NUMPY="1.12"
    - env: MODE="test" PYTHON="2.7" NUMPY="1.13"
    - env: MODE="test" PYTHON="2.7" NUMPY="1.14"
    # <=1.12 not packaged for py34 in conda
    - env: MODE="test" PYTHON="3.4" NUMPY="1.11"
    - env: MODE="test" PYTHON="3.5"
    - env: MODE="test" PYTHON="3.6" COVERAGE="true" SCIPY="true"
    - env: MODE="docs" PYTHON="3.6"
    - stage: deploy
      if: branch =~ ^release-candidate-* OR tag =~ ^v[0-9]*
      env: MODE="deploy" PYTHON="3.6"
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          user: tbekolay
          password: $PYPI_TOKEN
          distributions: "sdist bdist_wheel"
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^release-candidate-*
            condition: $TRAVIS_TAG = ""
        - provider: pypi
          user: tbekolay
          password: $PYPI_TOKEN
          distributions: "sdist bdist_wheel"
          on:
            all_branches: true
            condition: $TRAVIS_TAG =~ ^v[0-9]*

before_install:
  - chmod +x .ci/deploy.sh  # so we can keep it -x on local machines
  - source .ci/conda.sh install

install:
  - .ci/$MODE.sh install

script:
  - .ci/$MODE.sh script

after_success:
  - .ci/$MODE.sh after_success

after_script:
  - .ci/$MODE.sh after_script
