language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  global:
    - PIP_WHEEL_COMMAND="pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors"  # Thanks astropy!
matrix:
  include:
    - python: 2.7
      env: TOXENV=pep8
before_install:
  - pip install --upgrade pip setuptools  # For wheel support
install:
  - if [[ "$TOXENV" == "pep8" ]]; then pip install tox; fi
  - if [[ "$TOXENV" != "pep8" ]]; then $PIP_WHEEL_COMMAND -r requirements.txt; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.6" && "$TOXENV" != "pep8" ]]; then $PIP_WHEEL_COMMAND -r requirements-test-py26.txt; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" && "$TOXENV" != "pep8" ]]; then $PIP_WHEEL_COMMAND -r requirements-test.txt; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TOXENV" != "pep8" ]]; then $PIP_WHEEL_COMMAND coverage pytest-cov coveralls; fi
script:
  - if [[ "$TOXENV" == "pep8" ]]; then tox; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TOXENV" != "pep8" ]]; then py.test --cov-config .coveragerc --cov nengo -n 2 -v; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.7" ]]; then py.test -n 2 -v; fi
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TOXENV" != "pep8" ]]; then coveralls; fi
notifications:
  email:
    - tbekolay@gmail.com