language: c
sudo: false
notifications:
  email:
    - tbekolay@gmail.com

cache:
  directories:
    - $HOME/miniconda

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - NUMPY="1.11"
    - SCIPY="false"
    - COVERAGE="false"
    - STATIC="false"
    - CONDA_DEPS="matplotlib jupyter"
    - PIP_DEPS="pytest pytest-xdist"

matrix:
  include:
    - env: PYTHON="2.7" COVERAGE="true"
    - env: PYTHON="2.7" STATIC="true"
    - env: PYTHON="2.7" NUMPY="1.7"
    - env: PYTHON="2.7" NUMPY="1.8"
    - env: PYTHON="2.7" NUMPY="1.9"
    - env: PYTHON="2.7" NUMPY="1.10"
    - env: PYTHON="3.4"
    - env: PYTHON="3.5" COVERAGE="true"
    - env: PYTHON="3.5" COVERAGE="true" SCIPY="true"

git:
  depth: 3

# Setup Miniconda
before_install:
  - export PATH="$MINICONDA_DIR/bin:$PATH";
  - if [ -d "$MINICONDA_DIR" ] && [ -e "$MINICONDA_DIR/bin/conda" ]; then
      echo "Miniconda already installed in $MINICONDA_DIR";
    else
      rm -rf "$MINICONDA_DIR";
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p "$MINICONDA_DIR";
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda create -q -n test python="$PYTHON" pip;
    fi
  - source activate test
  - conda info -a

# Install packages with conda, then pip
install:
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - if [[ "$COVERAGE" == "true" ]]; then
      export PIP_DEPS="pytest coverage";
    elif [[ "$STATIC" == "true" ]]; then
      export CONDA_DEPS="";
      export PIP_DEPS="flake8 pylint";
    fi
  - if [[ -n "$NUMPY" && "$STATIC" == "false" ]]; then
      export CONDA_DEPS="$CONDA_DEPS numpy=$NUMPY";
    fi
  - if [[ "$SCIPY" == "true" ]]; then
      export CONDA_DEPS="$CONDA_DEPS scipy";
    fi
  - if [[ -n "$CONDA_DEPS" ]]; then eval conda install "$CONDA_DEPS"; fi
  - if [[ -n "$PIP_DEPS" ]]; then eval pip install "$PIP_DEPS" --user; fi

# Run the tests
script:
  - mkdir -p "$HOME/.ipython/profile_default"
  - "echo 'c.HistoryAccessor.enabled = False\n' > $HOME/.ipython/profile_default/ipython_config.py"
  - if [[ "$STATIC" == "false" ]]; then
      python -c "import numpy; numpy.show_config()";
      python setup.py -q develop;
      if [[ "$COVERAGE" == "false" ]]; then
        py.test nengo -n 2 -v --duration 20;
      else
        coverage run --rcfile .coveragerc --source nengo -m py.test nengo -v --duration 20 && coverage report;
      fi
    else
      flake8 -v nengo && pylint nengo;
    fi

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then
      eval "bash <(curl -s https://codecov.io/bash)";
    fi
