environment:
  matrix:
    - PYTHON: "C:\\Miniconda"
    - PYTHON: "C:\\Miniconda3"
    - PYTHON: "C:\\Miniconda35-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install numpy matplotlib jupyter pytest

build: false  # Not a C# project

test_script:
  - python setup.py -q develop
  - pytest nengo -v --durations=20
